"""is_admin added

Revision ID: 167ad878b6c3
Revises: ed44011a60c3
Create Date: 2023-03-28 15:08:14.243654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167ad878b6c3'
down_revision = 'ed44011a60c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
